name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION_OLDEST: "3.10.6"
  FLUTTER_VERSION_NEWEST: "3.38.7"

jobs:
  test:
    name: Test (newest Flutter version)
    runs-on: codeberg-small

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.forgejo/actions/setup-flutter
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_NEWEST }}

      - name: Dependencies (core)
        working-directory: refena
        run: dart pub get
      - name: Check format (core)
        working-directory: refena
        run: dart format --set-exit-if-changed lib bin test
      - name: Analyze (core)
        working-directory: refena
        run: flutter analyze
      - name: Test (core)
        working-directory: refena
        run: dart test

      - name: Dependencies (flutter)
        working-directory: refena_flutter
        run: flutter pub get
      - name: Check format (flutter)
        working-directory: refena_flutter
        run: dart format --set-exit-if-changed lib bin test
      - name: Analyze (flutter)
        working-directory: refena_flutter
        run: flutter analyze
      - name: Test (flutter)
        working-directory: refena_flutter
        run: flutter test

      - name: Dependencies (inspector)
        working-directory: refena_inspector
        run: flutter pub get
      - name: Test (inspector)
        working-directory: refena_inspector
        run: flutter test

      - name: Dependencies (riverpod extension)
        working-directory: refena_riverpod_extension
        run: flutter pub get
      - name: Test (riverpod extension)
        working-directory: refena_riverpod_extension
        run: flutter test

  test_legacy:
    name: Test (oldest Flutter version)
    runs-on: codeberg-small

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.forgejo/actions/setup-flutter
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_OLDEST }}

# the "test" package has invalid dependency constraints
#      - name: Downgrade (core)
#        working-directory: refena
#        run: dart pub downgrade
      - name: Dependencies (core)
        working-directory: refena
        run: dart pub get
      - name: Test (core)
        working-directory: refena
        run: dart test

# the "test" package has invalid dependency constraints
#      - name: Downgrade (flutter)
#        working-directory: refena_flutter
#        run: flutter pub downgrade
      - name: Dependencies (flutter)
        working-directory: refena_flutter
        run: flutter pub get
      - name: Test (flutter)
        working-directory: refena_flutter
        run: flutter test
